### ISSUE TITLE
안녕하세요 잘보고갑니다!

### ISSUE THREAD

**Issue by changchanghwang** [Sinclebear/nodejsplus_blog#1]
안녕하세요 항해3기 황창환입니다.

조금이나마 미약하지만 도움이되고자 코멘트 남깁니다!

1. https://github.com/Sinclebear/nodejsplus_blog/blob/b1d9aee223921ba36966be4b4918aaab3772dde1/app.js#L17-L29
위와같이 db정보가 public repository에 노출되면 좋지 않습니다. 이 경우 환경변수로 관리해주는것이 보안상으로 더 좋습니다.
(참고:https://www.npmjs.com/package/dotenv)

2. res.send와 res.json을 혼용해서 사용하시고 계신데 어차피 객체로 response를 보낸다면 res.json이 조금 더 좋은 선택이 될 수 있습니다.

참고:https://haeguri.github.io/2018/12/30/compare-response-json-send-func/

3. try/catch 를 이용하여 에러핸들링을 하면 조금 더 좋은 코드를 짤 수 있습니다!
참고:[try/catch](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/try...catch)
참고:[express error-handling](https://expressjs.com/ko/guide/error-handling.html)

4. 추가질문과 관련되어 있는 내용같은데 
https://github.com/Sinclebear/nodejsplus_blog/blob/b1d9aee223921ba36966be4b4918aaab3772dde1/app.js#L38-L67
이 코드같은 경우에 db에 두번 접근하고 그사이에 map으로 반복문을 한번 더 쓰게되면 나중에 데이터가 무수히 많아졌을때 서버가 많이 힘들어 할 수 있습니다. (불필요한 반복문은 성능저하에 크게 영향을 미쳐 좋지 않습니다!)

관계형 데이터베이스를 쓰게되면 db에 두번 접근할 필요 없이 Join문을 활용하여 한번에 두가지 컬럼을 찾을 수 있게 됩니다. nosql(몽고db)의 경우 join문이 없어 aggregate나 populate를 쓰게되면 기존 코드보다 훨씬 빠르게 동작 할 수 있습니다.

5. 그리고 app.js에 모든 로직을 거의 대부분 써 놓으셨는데, 이는 나중에 코드가 길어지게되면 유지보수하기 매우 힘든 코드가 됨으로 폴더나 파일로 나누어서 모듈화 하는것이 좋을 것 같습니다!
mvc패턴 같은 것을 참조하시면 조금 더 좋지 않을까 싶습니다.

너무 잘하셔서 말할게 몇가지 없네요! 남은 항해기간도 화이팅입니다~!

**Comment by Sinclebear** [comment]
안녕하세요! 꼼꼼한 코멘트 감사드립니다. 

1. 별도 파일을 만들어서 데이터베이스 서버 주소, jwt 시크릿 키 등을 담으려고 했는데 dotenv 라는게 있군요. 현재 유사한 미니 프로젝트를 진행중인데, 그쪽에 우선 적용해보겠습니다.
2. 강의에서 다루었던 코드와 기존에 사용하던 코드가 혼용되어 하나로 통일하고 싶었는데, 어떤게 더 효율적인지 잘 인지하지 못해 보류상태로 두었습니다. 잘 읽어보고 적용해보겠습니다.
3. 현재는 if-else if 구문으로 에러 처리를 하고있는데 이를 try-catch 문으로 감싸서 실패하는 케이스를 전부 catch 로 넘기면 가독성이 좀더 좋아질 것 같다는 생각이 드네요.
4. 현재 쿼리를 여러번 보내는데 aggregate, populate로 쿼리 한줄에 원하는 정보를 가져오도록 한번 시도해보겠습니다.
5. 현재 진행중인 미니프로젝트에서는 router 별로 나누어서 작성중에 있습니다. 작업이 완료되고 이 프로젝트에도 적용해보도록 하겠습니다.

귀중한 주말 시간내주셔서 정말 감사합니다. 하시는 일 모두 잘 되시길 바라겠습니다.

**Comment by changchanghwang** [comment]
> 안녕하세요! 꼼꼼한 코멘트 감사드립니다.
> 
> 1. 별도 파일을 만들어서 데이터베이스 서버 주소, jwt 시크릿 키 등을 담으려고 했는데 dotenv 라는게 있군요. 현재 유사한 미니 프로젝트를 진행중인데, 그쪽에 우선 적용해보겠습니다.
> 2. 강의에서 다루었던 코드와 기존에 사용하던 코드가 혼용되어 하나로 통일하고 싶었는데, 어떤게 더 효율적인지 잘 인지하지 못해 보류상태로 두었습니다. 잘 읽어보고 적용해보겠습니다.
> 3. 현재는 if-else if 구문으로 에러 처리를 하고있는데 이를 try-catch 문으로 감싸서 실패하는 케이스를 전부 catch 로 넘기면 가독성이 좀더 좋아질 것 같다는 생각이 드네요.
> 4. 현재 쿼리를 여러번 보내는데 aggregate, populate로 쿼리 한줄에 원하는 정보를 가져오도록 한번 시도해보겠습니다.
> 5. 현재 진행중인 미니프로젝트에서는 router 별로 나누어서 작성중에 있습니다. 작업이 완료되고 이 프로젝트에도 적용해보도록 하겠습니다.
> 
> 귀중한 주말 시간내주셔서 정말 감사합니다. 하시는 일 모두 잘 되시길 바라겠습니다.

4번 같은 경우에는 제가 mongoDB를 오래 써보지를 않아서 정확하게 populate와 aggregate에서 어떤결과가 나오기위해서 어떤 메서드를 쓰면 좋을지를 아직 제가 예측이 조금 힘듭니다. 다만 말씀하신것처럼 한번에 작동을 시키고 싶으시다면 mysql이 조금더 현 서비스에 적합한 데이터베이스라는 생각이 듭니다 :) 

좋은 주말되세요~!
