### ISSUE TITLE
안녕하세요! 과제 코멘트 남겨드리고 갑니다!

### ISSUE THREAD

**Issue by archepro84** [Sinclebear/nodejsplus_blog#2]
안녕하세요! 항해99 2기 수료생 이용우입니다. 서비스 잘 보고 갑니다.

몇 가지 궁금한 점이 있어 질문드립니다.

1. 모든 비즈니스 로직들이 app.js 파일에 정의되어 있는 것 같습니다. 
    - Router의 역할 마다 Router 파일을 생성하게 될 경우 이후 코드를 분석할 때 효율적일 것 같습니다.
    - 동일한 역할을 하는 Router를 1개의 파일로 합칠 경우 URI를 동시에 관리할 수 있어 수정하는데 효율적일 것 같습니다.
2. 예외 처리 되지 않은 라우터들이 많은 것 같습니다.
    - 예외 처리되지 않은 라우터에서 에러가 발생할 경우 서버가 멈추거나, 종료될 수 있습니다.
    - 에러 상황은 언제든지 발생할 수 있으므로 예외 처리를 추가하면 좋을 것 같습니다.
    - 참고: [expressjs Exception](https://expressjs.com/ko/guide/error-handling.html)
3. 민감한 정보는 .env 파일로 분리하여 별도로 관리하는것이 좋을 것 같습니다.
    - dotenv 패키지를 이용해 보안이 필요한 정보들을 관리하면 더욱 안전한 코드가 될 것 같습니다.
    
    ```jsx
    // app.js
    // Before
    mongoose.connect("mongodb://localhost/nodejsplus_blogdb", {}
    
    // After
    const DB_HOST = process.env.DB_HOST
    const DB_SCHEMA = process.env.DB_SCHEMA
    const dbUrl = `mongodb://${DB_HOST}/${DB_SCHEMA}`
    
    mongoose.connect(dbUrl, { }
    ```
    

추가적으로 질문 남겨주신 내용을 답변드리자면

- RawQuery를 사용하여 1번의 가져오게 될 경우 가공된 정보를 쉽게 가져올 수 있습니다.
    - 하지만 이후 코드를 분석하거나 수정하는 과정에서 많은 시간이 소모될 수 있습니다.
- 여러 번 쿼리를 사용하고 조합해서 내보는것은 통신 횟수가 많아져 DB가 부담될 수 있습니다.
    - 하지만 코드를 분석할 때 한눈에 이해할 수 있어 효율적입니다.
- 결국, 코드를 수정하거나 분석하기 효율적인 것은 여러 번 통신하는 것이지만, 이후 TypeORM과 같은 ORM를 사용하면서 비교하는 것이 더 좋은 방법일 것 같습니다.

과제 수행하시느라 고생많으셨습니다!

**Comment by Sinclebear** [comment]
안녕하세요! 과제 리뷰 및 코멘트 감사드립니다.
1. 현재 진행중인 미니 팀프로젝트에서 라우터별로 나누어서 작성중에 있습니다. 추후에 이 프로젝트에도 적용해보도록 하겠습니다.
2. 에러 발생 시 초기화면으로 돌려보내는등 처리를 해야 꺼지지 않겠네요. 현재는 다시 수동으로 켜주고있긴 하지만 서비스로 운영 시 문제가 되겠습니다.
3. dotenv 패키지라는게 있군요. 현재 이 프로젝트와 유사한 미니 팀 프로젝트를 진행중인데, 해당 프로젝트에 적용해보겠습니다.
RawQuery 관련 : 작성해주신 RawQuery 방식과 ORM/ODM 사용 시 장단점이 확실히 있겠네요. 서비스를 구상할 때 데이터베이스 구성 및 사용에 대해 좀 더 많은 고민이 필요하다고 생각이 듭니다.

늦은 시간 피드백 감사드립니다. 하시는 일 모두 잘 되시길 바라겠습니다!
